name: Run unit tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
permissions:
  contents: write
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
      id: go
    - name: Set up DB + Migrations
      uses: hoverkraft-tech/compose-action@v2.1.0
      with:
        compose-file: "./docker-compose.infra.yaml"
        down-flags: "--volumes"

    - name: go test
      run: make test-with-coverage
    - name: check test coverage
      uses: vladopajic/go-test-coverage@v2
      with:
        profile: cover.out
        git-token: ${{ github.ref_name == 'master' && secrets.GITHUB_TOKEN || '' }}
        # https://github.com/vladopajic/go-test-coverage/blob/main/docs/badge.md#hosting-the-coverage-badge-in-the-same-github-repository
        ## name of branch where badges are stored
        ## ideally this should be orphan branch (see below how to create this branch)
        git-branch: badges       
