name: Run unit tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
      id: go
    - name: Set up DB + Migrations
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./docker-compose.infra.yaml"
        down-flags: "--volumes"

    - name: go test
      run: make test
